
// CLEAN SLATE SCHEMA - STRATIFY DIRECTOR SWARM
// Corresponds to User's 8-Point Plan - Step A

export type AspectRatio = '16:9' | '9:16' | '21:9' | '4:3';
export type ContentRating = 'family' | 'teen' | 'mature';
export type VisualMode = 'realistic' | 'stylized' | 'animated';
export type LipSyncMode = 'none' | 'lead' | 'backing' | 'group';

// 1. INFLUENCE DIALS (The 10 Cinematic Traits)
export interface InfluenceDials {
    blockingPrecision: number;   // 0-100: Staging & movement rigor
    motivatedCamera: number;     // 0-100: Move only when story demands
    wonderAndScale: number;      // 0-100: EWS + Drone reveals
    intimateEmotion: number;     // 0-100: CU/ECU + Shallow DOF
    rhythmicMontage: number;     // 0-100: Cut speed/patterns
    naturalism: number;          // 0-100: Handheld realism
    stylizedSymmetry: number;    // 0-100: Wes Anderson / Kubrick formal comp
    highContrastMood: number;    // 0-100: Noir / Neon
    longTakeConfidence: number;  // 0-100: 6-12s shots vs rapid cuts
    iconicHeroFrames: number;    // 0-100: Poster-worthy chorus shots
}

export interface DirectorProfile {
    influenceDials: InfluenceDials;
    narrativePreference: 'performance-first' | 'story-first' | 'hybrid';
    colorGrade?: string;
    notes?: string;
}

// 2. CAST & CHARACTERS
export interface Character {
    characterId: string;
    name: string;
    role: 'lead' | 'band-member' | 'actor' | 'extra';
    genderPresentation: 'male' | 'female' | 'non-binary';
    ageRange: string;
    lookSpec: {
        hair?: string;
        face?: string;
        physique?: string;
        style?: string; // e.g. "Punk Rock"
    };
    wardrobeSignature: string[]; // e.g. ["Leather Jacket", "Sunglasses"]
    instrument?: string;
    referenceImage?: string; // URL/Path to uploaded image
    consistencyMode?: boolean; // Force this face/look across all shots
    extractedVisuals?: {     // AI-Analyzed details
        face: string;
        wardrobe: string;
        vibe: string;
    };
}

export interface CastList {
    lead: Character;
    band: Character[];
    principals: Character[]; // Non-musician actors
}

// 3. SONG DATA (Intake)
export interface SongData {
    title: string;
    artist: string;
    bpm: number;
    genre: string;
    subGenre?: string;
    duration?: string; // e.g. "3:30"
    audioFile?: string; // Filename for Veo/Tool lip-sync
    audioFileOverride?: string; // Manual URL/Filename override
    lipSyncEnabled?: boolean; // User toggle
    lyrics: {
        rawText: string;
        sections?: {
            label: string; // Verse 1, Chorus
            lines: { text: string; startSec: number; endSec: number }[];
        }[];
    };
    moodKeywords: string[];
}

// 4. SHOT STRUCTURE (The Atomic Unit)
export interface CameraSpec {
    movement: 'locked' | 'pan' | 'tilt' | 'dolly-in' | 'dolly-out' | 'truck-left' | 'truck-right' | 'orbit' | 'crane-up' | 'crane-down' | 'handheld' | 'drone' | 'zoom-in' | 'zoom-out';
    angle: 'eye-level' | 'low-angle' | 'high-angle' | 'dutch' | 'overhead';
    lensFeel: 'wide' | 'normal' | 'telephoto' | 'macro' | 'fisheye';
    motionSpeed?: 'slow' | 'normal' | 'fast';
}

export interface ShotSubject {
    characterId: string;
    screenPosition: 'left' | 'center' | 'right' | 'background';
    action: string;
    purpose: 'singing' | 'acting' | 'reacting' | 'instrument';
}

export interface AudioSync {
    mode: LipSyncMode;
    lyricLineText?: string; // The exact line to sync
    startSec: number;
    endSec: number;
}

export interface Shot {
    shotId: string;
    index: number;
    sceneId: string;

    // Core Visuals
    shotType: 'EWS' | 'WS' | 'MS' | 'MCU' | 'CU' | 'ECU';
    camera: CameraSpec;
    lighting: { style: string; source?: string };

    // Content
    action: string; // The primary visual description (Deprecated/Summary)
    foregroundAction: string;
    backgroundAction: string;
    subjects: ShotSubject[];
    composition: string; // e.g. "Rule of thirds", "Center framed"
    basePrompt: string; // The neutral, tool-agnostic prompt

    // Audio
    durationSec: number;
    audioEnvironment: string; // e.g. "Rain sounds", "City noise"
    audioSync: AudioSync;

    // Tool-Specific Prompts (Generated by Compiler)
    toolPrompts?: {
        veo?: string;
        veo3?: string;
        imagen3?: string;
        runway?: string;
        luma?: string;
        kling?: string;
        pika?: string;
        ue5?: string;
    };

    // QC Flags
    qcIssues?: string[];
}

// 5. SCENE STRUCTURE
export interface Scene {
    sceneId: string;
    index: number;
    title: string; // e.g. "Verse 1 - The Bedroom"
    locationId: string;
    mood: {
        visual: string;
        lighting: string;
        color: string;
        ambience: string; // Sound/Vibe
    };
    narrativeBeat: string;
    shots: Shot[];
}

export interface Location {
    locationId: string;
    name: string;
    description: string;
    timeOfDay: 'dawn' | 'day' | 'dusk' | 'night';
    weather: 'clear' | 'cloudy' | 'rain' | 'storm' | 'fog';
    // New Fields for Director Mode
    blocking?: string; // e.g. "Actor walks from left to center, stops at mark."
    extras?: string; // e.g. "Crowd of teens-Background dancers"
    audioEnvironment?: string; // e.g. "Street noise, distant sirens, clear dialogue"
    colorPalette?: string; // e.g. "60% Midnight Blue, 30% Neon Pink, 10% White"
    lighting?: string; // e.g. "Neon Noir", "Soft Natural", "Studio High Key"
    cameraVibe?: string; // e.g. "Handheld Chaos", "Smooth Steadicam", "Static Tripod"
    artDirection?: string; // e.g. "Minimalist", "Cluttered/Messy", "Futuristic"
}

export interface Treatment {
    id: string;
    title: string;
    summary: string;
    locations?: Location[];
}

// 6. MASTER PROJECT OBJECT
export interface StratifyProject {
    projectId: string;
    version: number;

    // User Intents
    song: SongData;
    cast: CastList;
    locations: Location[];

    // Director Brain
    project: {
        summary: string;
        notes?: string; // User's initial idea
        directorProfile: DirectorProfile & {
            coreThemes?: string[]; // New: AI-detected themes
        };
        outputSpec: {
            aspectRatio: AspectRatio;
            resolution: '1080p' | '4k';
            contentRating: ContentRating;
            visualMode: VisualMode;
        };
    };

    // The Script
    treatments?: Treatment[]; // Pitch phase
    selectedTreatmentId?: string;

    scenes: Scene[]; // The Sequence

    // Export Data
    edl?: any; // Edit Decision List structure
}
